version: '3'
services:
  backend:
    image: luchen2001/180markets:180backend
    ports:
      - 8000:8000
    restart: always
  frontend:
    image: luchen2001/180markets:180frontend
    ports:
      - 80:3000
    restart: always
